name: Upload
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  upload:
    name: Upload Kernel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/push-kaggle-kernel@master
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          slug: test-script
          title: test-script
          code_file: house-prices-advanced-regression-techniques.py
          language: python
          kernel_type: script
          is_private: true
          competition_sources: |
            house-prices-advanced-regression-techniques
